import { Box, Heading, ListItem, OrderedList, Text, UnorderedList } from "@chakra-ui/react";
import MainTemplate from "../../../components/Client/Templates/Main";

export default function UserRoles() {
    return (
        <MainTemplate>
            <Box p={'2rem'} fontSize={'1.1rem'}>
                <Heading mb={'2rem'} size={'lg'}>User and Roles</Heading>

                <Text>The email addresses for your Primary Account Information, Your Videeo Account, and Your Business Profile should all be consistent. If you make an email change, your new email address will become your Videeo sign-in credential. For more details, consult the Account Setup section. Issues with logging in or navigating specific parts of your account are often the result of using incorrect email and passwords.</Text>
                <Box my={'1rem'}>
                    <Heading mb={'0.5rem'} color={'#55DF01'} size={'md'}>In This Guide:</Heading>
                    <UnorderedList color={'#9c9c9c'}>
                        <ListItem>Authorize other users</ListItem>
                        <ListItem>Monitor invitation statuses</ListItem>
                        <ListItem>Alter access levels</ListItem>
                        <ListItem>Revoke access permissions</ListItem>
                    </UnorderedList>
                </Box>

                <Box my={'1rem'}>
                    <Heading mb={'0.5rem'} size={'md'} color={'#55DF01'}>Authorize Other Users:</Heading>
                    <Text>To maintain the security of your account, never share your login details. Instead, use the User Invitation feature to grant another individual access to your Videe0 account. You can adjust the level of access for each user you authorize. Note: By default, only Videeo account admins can view banking information. They may extend this access to other users as needed.</Text>
                    <br />
                    <Text>To send an invitation, the invitee should first provide you with a unique user code. This code can be generated by visiting https://account.videeo.com/user-code and signing in with a work email address. A multi-factor authentication process will be in place.</Text>
                </Box>

                <Box my={'1rem'}>
                    <Heading mb={'0.5rem'} size={'md'} color={'#55DF01'}>To Authorize a User:</Heading>
                    <OrderedList color={'#9c9c9c'}>
                        <ListItem>Navigate to videeo.com.</ListItem>
                        <ListItem>Click your username on the top right and select Your Account.</ListItem>
                        <ListItem>Under Your Account, click Users & Roles, then click Add User.</ListItem>
                        <ListItem>Input the unique user code provided by the invitee.</ListItem>
                        <ListItem>Enter their email address, which must match the one used to obtain the user code.</ListItem>
                        <ListItem>Choose the levels of permission to grant, then click Add User. To add more users, click Add Another User</ListItem>
                    </OrderedList>
                </Box>

                <Box my={'1rem'}>
                    <Heading mb={'0.5rem'} size={'md'} color={'#55DF01'}>Monitor Invitation Statuses <br />To see who has accepted your invitations:</Heading>
                    <Text>1. Go to Users & Roles, then click Accepted. To see pending invitations, click Pending.</Text>
                    <Text>Statuses Include: </Text>
                    <UnorderedList color={'#9c9c9c'}>
                        <ListItem>Pending: Invitation sent, but not yet accepted.</ListItem>
                        <ListItem>Unconfirmed: Invitation accepted, business profile incomplete.</ListItem>
                        <ListItem>Active: Invitation accepted and business profile complete. Access granted according to permissions.</ListItem>
                    </UnorderedList>
                </Box>

                <Box my={'1rem'}>
                    <Heading mb={'0.5rem'} size={'md'} color={'#55DF01'}>Modify Access Levels:</Heading>
                    <Text>To change an individual`s role or other profile information:</Text>
                    <OrderedList color={'#9c9c9c'}>
                        <ListItem>Click Users & Roles, then All Users</ListItem>
                        <ListItem>Choose Edit next to the individual`s entry, make your changes, and save.</ListItem>
                    </OrderedList>
                </Box>

                <Box my={'1rem'}>
                    <Heading mb={'0.5rem'} size={'md'} color={'#55DF01'}>Revoke Access</Heading>
                    <Text>To permanently remove someone`s access:</Text>
                    <OrderedList color={'#9c9c9c'}>
                        <ListItem>Go to Users & Roles, then All Users.</ListItem>
                        <ListItem>Click Delete next to the user`s name.</ListItem>
                    </OrderedList>
                </Box>

                <Box my={'1rem'}>
                    <Heading mb={'0.5rem'} size={'md'} color={'#55DF01'}>Warning:</Heading>
                    <Text>Deletion is irreversible; you`ll need to re-invite the user if you want to grant access later. If login issues persist, ensure you`re using the correct email and password. Multiple accounts linked to the same email address may result in login confusion.</Text>
                </Box>
            </Box>
        </MainTemplate>
    );
}