export const VideoData = [
    {
        id: '1',
        name: 'The Dark Web',
        Type: 'Adventure',
        views: '59k',
        upload: '2/12/2022',
        Rented_Amount: '45',
        Purchasing_Amount: '80',
        desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequuntur cum ratione sunt nisi nemo distinctio, ea reiciendis iste alias incidunt illo laborum labore doloremque architecto non, qui, sapiente voluptas. Repudiandae assumenda officia soluta suscipit animi ullam velit? Quasi quisquam unde distinctio illo minus impedit eum libero, incidunt repellendus molestias id.',
        Genre: 'Thriller',
        Medium: 'Documentary',
        Crew: ['Tom Cruise', 'Angelina Jolie', 'Brad pitt'],
        url: 'https://www.youtube.com/watch?v=COv52Qyctws',
    },
    {
        id: '2',
        name: 'Lost Treasure',
        Type: 'Mystery',
        views: '72k',
        upload: '3/5/2022',
        Rented_Amount: '60',
        Purchasing_Amount: '100',
        desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequuntur cum ratione sunt nisi nemo distinctio, ea reiciendis iste alias incidunt illo laborum labore doloremque architecto non, qui, sapiente voluptas. Repudiandae assumenda officia soluta suscipit animi ullam velit? Quasi quisquam unde distinctio illo minus impedit eum libero, incidunt repellendus molestias id.',
        Crew: ['Tom Cruise', 'Angelina Jolie', 'Brad pitt'],
        url: 'https://www.youtube.com/watch?v=COv52Qyctws',
    },
    {
        id: '3',
        name: 'Space Explorers',
        Type: 'Sci-Fi',
        views: '45k',
        upload: '1/20/2022',
        Rented_Amount: '55',
        Purchasing_Amount: '90',
        desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequuntur cum ratione sunt nisi nemo distinctio, ea reiciendis iste alias incidunt illo laborum labore doloremque architecto non, qui, sapiente voluptas. Repudiandae assumenda officia soluta suscipit animi ullam velit? Quasi quisquam unde distinctio illo minus impedit eum libero, incidunt repellendus molestias id.',
        Crew: ['Tom Cruise', 'Angelina Jolie', 'Brad pitt'],
        url: 'https://www.youtube.com/watch?v=COv52Qyctws',
    },
    {
        id: '4',
        name: 'Ancient Mysteries',
        Type: 'History',
        views: '37k',
        upload: '4/15/2022',
        Rented_Amount: '50',
        Purchasing_Amount: '85',
        desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequuntur cum ratione sunt nisi nemo distinctio, ea reiciendis iste alias incidunt illo laborum labore doloremque architecto non, qui, sapiente voluptas. Repudiandae assumenda officia soluta suscipit animi ullam velit? Quasi quisquam unde distinctio illo minus impedit eum libero, incidunt repellendus molestias id.',
        Crew: ['Tom Cruise', 'Angelina Jolie', 'Brad pitt'],
        url: 'https://www.youtube.com/watch?v=COv52Qyctws',
    }

]